config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from balystic import views as balystic_views
from ckeditor_uploader import views as ckeditor_views
from seoq.core import views as core_views
from seoq.payments_seoq import views as payments_seoq
from seoq.users.views import UserUpdateRedirect

from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^$', core_views.HomeView.as_view(template_name='pages/home.html'),
        name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'),
        name='about'),
    # Needed cause django-braces uses the account prefix for LoginRequiredMixin
    url(r'^accounts/login/$',
        balystic_views.LoginView.as_view(), name='account_login'),
    url(r'^accounts/login/$',
        balystic_views.LoginView.as_view(), name='balystic_login'),
    url(r'^accounts/logout/$',
        balystic_views.LogoutView.as_view(), name='balystic_logout'),
    url(r'^users/edit/(?P<username>[-\w.+]+)/$',
        UserUpdateRedirect.as_view(),
        name='balystic_user_update'),
    url(r'^accounts/signup/$',
        balystic_views.UserSignupView.as_view(), name='balystic_signup'),
    url(r'^seo-directory/$', core_views.SEODirectoryUserList.as_view(),
        name='directory'),

    url(r'^seo-directory/(?P<username>[\w.@+-]+)/$',
        core_views.PublicUserDetailView.as_view(),
        name='public_profile'),

    url(r'^website-owners/$',
        TemplateView.as_view(template_name='pages/owners.html'),
        name='owners'),
    # url(r'^join/$', TemplateView.as_view(template_name='pages/join.html'),
    #     name='join'),
    url(r'^seo-professionals/$', TemplateView.as_view
        (template_name='pages/professionals.html'),
        name='professionals'),
    url(r'^seo-students/$', TemplateView.as_view
        (template_name='pages/students.html'),
        name='students'),
    url(r'^order/(?P<pk>\d+)/$',
        payments_seoq.OrderView.as_view(), name='order'),
    url(r'^order/(?P<pk>\d+)/payment/success/$',
        payments_seoq.OrderPaymentReturnView.as_view(status='success'),
        name='order_payment_success'),
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),
    url(r'^ckeditor/upload/',
        ckeditor_views.upload, name='ckeditor_upload'),
    url(r'^ckeditor/browse/', ckeditor_views.browse, name='ckeditor_browse'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url('^markdown/', include( 'django_markdown.urls')),

    # User management
    url(r'^', include('seoq.users.urls', namespace='users')),
    # url(r'^qa/.*$',
    #     RedirectView.as_view(
    #         url='http://seoq.app.balystic.com/questions-and-answers/',
    #         permanent=False), name='balystic_qa'),
    url(r'^', include('balystic.urls')),
    url(r'^', include('seoq.seoqtool.urls', namespace='seoqtool')),
    url(r'^', include('plans.urls')),

    # Your stuff: custom urls includes go here
    # CompaniesRedirectView
    url(r'^seo-companies/(?P<slug>[-\w.]+)/$',
        core_views.CompaniesRedirectView.as_view(),
        name='seo_companies_redirect'),
    url(r'^(?P<slug>[-\w.]+)/$',
        core_views.ArchivedBlogRedirectView.as_view(), name='archived_blog'),
    url(r'^robots.txt$', core_views.RobotsView.as_view())

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

seoq/seoqtool/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^www/(?P<netloc>[\w_\-\.]+)/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]{2})/$',
        view=views.ArchiveReportView.as_view(),
        name='archive_report'
    ),
    url(
        regex=r'^add-url/$',
        view=views.CreateReportURLView.as_view(),
        name='add_url'
    ),
]

seoq/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^users/$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # url(
    #     regex=r'^user_list/$',
    #     view=views.UserListTempView.as_view(),
    #     name='list'
    # ),

    # url(
    #     regex=r'^user-list-recent/$',
    #     view=views.UserListMostRecentTempView.as_view(),
    #     name='list'
    # ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^users/~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^users/(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    #URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

seoq/asynchronous/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

seoq/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from plans.signals import activate_user_plan
from django.db.models import signals
from django.contrib.postgres.fields import JSONField, ArrayField


@python_2_unicode_compatible
class User(AbstractUser):

    EXPERTISE_CHOICES = (
        ('Technical SEO', 'Technical SEO'),
        ('Writer/Blogger', 'Writer/Blogger'),
        ('Google Analytics', 'Google Analytics'),
        ('Link Builder', 'Link Builder'),
        ('SEO Training', 'SEO Training'),
        ('Social Media', 'Social Media'),
        ('Keyword Analyst', 'Keyword Analyst'),
    )

    LANGUAGE_CHOICES = (
        ('English', 'English'),
        ('French', 'French'),
        ('Spanish', 'Spanish'),
        ('German', 'German'),
        ('Portuguese', 'Portuguese'),
    )

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)
    phone_number = models.CharField(blank=True, max_length=50)
    fb_account = models.URLField(blank=True, max_length=255)
    twitter_account = models.URLField(blank=True, max_length=255)
    linkedin_account = models.URLField(blank=True, max_length=255)
    google_account = models.URLField(blank=True, max_length=255)
    skype = models.CharField(max_length=50, blank=True, default='')
    title = models.CharField(blank=True, max_length=255)
    about = models.TextField(_("About You"), blank=True, default='')
    location = models.CharField(blank=True, max_length=255)
    profile_picture = models.ImageField(
        blank=True,
        null=True,
        upload_to='profile/')
    generics = JSONField(default=dict)
    company_name = models.CharField(blank=True, max_length=255)
    company_logo = models.ImageField(
        blank=True,
        null=True,
        upload_to='profile/')
    website_url = models.URLField(blank=True, max_length=255)
    areas_of_expertise = ArrayField(
        models.CharField(max_length=50, blank=True,
                         choices=EXPERTISE_CHOICES, default=''),
        default=list
    )
    areas_of_expertise_other = models.CharField(
        max_length=50, blank=True, default='')
    languages = ArrayField(
        models.CharField(max_length=50, blank=True,
                         choices=LANGUAGE_CHOICES, default=''),
        default=list
    )
    languages_other = models.CharField(max_length=50, blank=True, default='')

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})


def user_signed_up_(sender, instance, created, **kwargs):
    """
    Whenever a user signs up, they should be added
    to the default plan.
    """
    activate_user_plan.send(sender=sender, user=instance)

signals.post_save.connect(user_signed_up_, sender=User, weak=False,
                          dispatch_uid='models.user_signed_up_')

seoq/core/forms.py
from django import forms

# our new form
class UserContactForm(forms.Form):
    first_name = forms.CharField(label='First name', required=True)
    last_name = forms.CharField(label='Last name',required=True)
    location = forms.CharField(label='Location',required=True)
    phone = forms.CharField(label='Phone',required=True)
    email = forms.EmailField(label='Email',required=True)
    content = forms.CharField(
        required=True,
        widget=forms.Textarea
    )

    def __init__(self, *args, **kwargs):
        super(UserContactForm, self).__init__(*args, **kwargs)
        for field_name in self.fields:
           field = self.fields.get(field_name)  
           if field:
               field.widget.attrs.update({
               		'placeholder': field.label,
               		'class': 'form-control'
               	})
        self.fields['content'].widget.attrs.update({
    		'placeholder': 'What do you want to say?',
    		'rows': 5
    	})

seoq/seoqtool/forms.py
from django import forms


class ExampleForm(forms.Form):
    url = forms.URLField(required=True, initial='http://')

seoq/asynchronous/views.py
from django.shortcuts import render

# Create your views here.

seoq/core/views.py
import json
from django.shortcuts import render, redirect
from django.views.generic import View, TemplateView
from django.views.generic.base import RedirectView
from django.http import Http404
from django.template.loader import render_to_string
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.conf import settings
from django.contrib import messages
from balystic.client import Client
from seoq.users.models import User
from .forms import UserContactForm


class SEODirectoryUserList(View):
    """
    Displays a list of the users retrieved from 7dhub
    """
    template_name = 'pages/users_directory_page.html'
    client = Client()

    def get(self, request):
        alphabetical = request.GET.get('alphabetical', None)
        query_term = request.GET.get('q', None)
        if query_term is None:
            params = {'isPro': '1', 'alphabetical': '1'}
        else:
            params = {'isPro': '1', 'q': query_term}
        context = {
            'users': self.client.get_users(params=params),
            'query_term': query_term
        }
        context['most_view_users'] = Client().get_users(
            {'sort_type': 'view_count'})['users'][:3]
        context['most_recent_users'] = Client().get_users(
            {'sort_type': 'last_created'})['users'][:3]
        context['most_votes_answer_users'] = Client().get_users(
            {'sort_type': 'answer_vote_count'})['users'][:3]
        context['verified_users'] = Client().get_users(
            {'sort_type': 'verified'})['users'][:3]
        return render(request, self.template_name, context)


class PublicUserDetailView(View):
    template_name = 'users/public_user_detail.html'
    form_class = UserContactForm

    def get(self, request, username):
        user = Client().get_user_detail(username)
        data = user['user'].copy()
        if not isinstance(data['generics'], dict):
            data['generics'] = json.loads(data['generics'])
        data.pop('avatar')
        username = data.pop('username')
        if "error" in user:
            raise Http404
        try:
            data['generics']['view_count'] += 1
        except (KeyError, TypeError):
            data['generics']['view_count'] = 1
        data['generics'] = json.dumps(data['generics'])
        Client().update_user(user['user']['username'], data)
        try:
            user_local = User.objects.get(username=username)
        except User.DoesNotExist:
            user_local = User()
        return render(
            request,
            self.template_name,
            {'user': user, 'user_local': user_local, 'form': self.form_class})

    def post(self, request, username):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            user_email = Client().get_user_detail(username)['user']['email']
            first_name = request.POST.get('first_name')
            last_name = request.POST.get('last_name')
            location = request.POST.get('location')
            phone = request.POST.get('phone')
            email = request.POST.get('email')
            content = request.POST.get('content')
            template = 'users/contact_template.html'
            template = render_to_string(
                template,
                {'form_content': content,
                 'contact_name': first_name + ' ' + last_name,
                 'contact_email': email,
                 'location': location,
                 'phone': phone})
            send_mail(
                first_name + " wants to contact you!",
                None,
                settings.DEFAULT_FROM_EMAIL,
                [user_email],
                html_message=template,
                fail_silently=False)
            messages.success(request, 'Email sent to ' + username)

            return redirect(
                reverse('public_profile', kwargs={'username': username}))


class ArchivedBlogRedirectView(RedirectView):
    """
    Redirect Original blog entries patterns to the new one
    """
    client = Client()

    def get_redirect_url(self, *args, **kwargs):
        slug = self.kwargs.get('slug')

        blog_entry = self.client.get_blog_detail(slug)
        if 'blog' not in blog_entry:
            raise Http404

        return reverse(
            'balystic_blog_detail',
            kwargs={'slug': blog_entry['blog']['slug']})


class CompaniesRedirectView(RedirectView):
    """
    Temporary Redirect of SEO users profiles while profiles are moved
    """
    def get_redirect_url(self, *args, **kwargs):
        slug = self.kwargs.get('slug')
        return settings.SEOQ_COMPANIES_URL + slug


class HomeView(TemplateView):
    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['qscraper_url'] = settings.QSCRAPER_URL
        return context

class RobotsView(TemplateView):
    template_name = 'core/robots.txt'

    def get_context_data(self, **kwargs):
        kwargs['environment'] = settings.PRODUCTION_ENVIRONMENT
        return kwargs

seoq/payments_seoq/views.py
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _
from django.shortcuts import redirect, render
from payments import RedirectNeeded, get_payment_model
from plans.models import Order
from plans.views import OrderView as ParentOrderView
from plans.views import OrderPaymentReturnView as ParentReturnView


class OrderView(ParentOrderView):
    model = Order
    template_name = 'plans/order_detail.html'

    def get_context_data(self, **kwargs):
        context = super(OrderView, self).get_context_data(**kwargs)
        payment, created = get_payment_model().objects.get_or_create(
            order__pk=self.object.pk,
            defaults={
                'variant': 'default',
                'description': 'Plan Purchase',
                'order': self.object,
                'total': self.object.total(),
                'tax': self.object.tax_total(),
                'currency': self.object.currency
            })
        context['payment_form'] = payment.get_form()
        context['payment'] = payment
        return context

    def post(self, request, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        try:
            context['payment_form'] = context['payment'].get_form(
                data=self.request.POST or None)
        except RedirectNeeded as redirect_to:
            return redirect(str(redirect_to))
        return render(request, self.template_name, context)


class OrderPaymentReturnView(ParentReturnView):
    """
    This view is a fallback from any payments processor. It allows just to set
    additional message context and redirect to Order view itself.
    """
    model = Order
    status = None

    def render_to_response(self, context, **response_kwargs):
        if self.status == 'success':
            messages.success(self.request,
                             _('Thank you for placing a payment. \
                                It will be processed as soon as possible.'))
        return redirect('/')

seoq/templates/users/contact_template.html
<p>{{ contact_name }} ({{ contact_email }}) says:</p>
<p>{{ form_content|safe|striptags }}</p>
<h2>{{ contact_name }}</h2>
<p>
Location: {{ location }}<br>
Phone: {{ phone }}<br>
</p>

seoq/templates/users/user_detail.html
{% extends "base.html" %}
{% load i18n staticfiles %}

{% block title %}User: {{ user.username }}{% endblock %}

{% block content %}
<div class="container p-t-50">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-1 m-b-30">

      <h2>{{ local_user.username }}</h2>
      {% if local_user.profile_picture %}
      <img src="{{ local_user.profile_picture.url }}" alt="" width="200" height="200">
      {% else %}
      <img src="{% static 'images/profile-default-thumbnail.jpg' %}" alt="" width="200" height="200">
      {% endif %}
      <br>
      {% if request.user.is_authenticated %}

      {% if user.user.username == request.user.username %}
        <a class="btn btn-primary m-t-20" href="{% url 'balystic_user_update' user.user.username %}">Update profile</a>
      {% endif %}
      {% if owner.username == request.user.username %}
      <a class="btn btn-primary m-t-20" href="http://seoq.app.balystic.com/customers/manage/seoq/">
        {% trans "Manage Community" %}
      </a>
      {% endif %}
      {% endif %}

    </div>
    <div class="col-sm-5 col-sm-offset-1 m-b-30">
      <p><strong>Name:</strong> {{ local_user.first_name }}</p>
      <p><strong>Last Name:</strong> {{ local_user.last_name }}</p>
      <p><strong>Email:</strong> {{ user.user.email }}</p>
      <p><strong>Bio:</strong> {{ local_user.about }}</p>
    </div>
    {% if user.user.username == request.user.username %}

    <div class="col-sm-5">
      <p><strong>{% trans "Account" %}:</strong> {{ user.user.username }}</p>
      <p><strong>{% trans "Plan" %}:</strong> {{ userplan.plan }} <a class="btn btn-sm btn-primary-ligth" href="{% url 'pricing' %}">{% trans "Upgrade" %}</a></p>
      <p><strong>{% trans "State" %}:</strong>
        {% if userplan.active %}
          {% trans "Active" %}
        {% else %}
          {% trans "Expired" %}
        {% endif %}
      </p>
      <p><strong>{% trans "Expiration date" %}:</strong> {{ userplan.expire }}</p>
    </div>
    {% endif %}
  </div>


{{ user.error }}

</div>
{% endblock content %}

seoq/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load i18n staticfiles %}

{% block title %}Edit profile{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2 p-t-20 p-b-70">
      <h3>{{ user.username }}</h3>
      <form class="form-horizontal" enctype='multipart/form-data' method="post" 
                action="">
        {% csrf_token %}
        <div class="form-group">
          <label for="id_profile_picture" class="control-label ">
            Profile pic
          </label>
          <div class="hidden">
            {{ form.profile_picture|as_crispy_field }}
          </div>
          {% if form.profile_picture.value != '' %}
            <img src="{{ MEDIA_URL }}{{ form.profile_picture.value }}" alt="profile" class="img-responsive center-block img-thumbnail" width="200" height="200" id="blah">
          {% else %}
            <img src="{% static 'images/profile-default-thumbnail.jpg' %}" id="blah" class="img-responsive img-thumbnail center-block" width="200" height="200">
          {% endif %}
          {% for error in form.profile_picture.errors %}
            <span class="help-block">
              {{ error|escape }}
            </span>
          {% endfor %}
        </div>
        <div class="row fieldWrapper form-group text-center">
          <label for="id_profile_picture" class="btn btn-primary">
            <span>Choose File</span> <i class="fa fa-camera" aria-hidden="true"></i>
          </label>
          {% if form.profile_picture.value != '' %}
            <label for="profile_picture-clear_id" id="reset" type="button" class="btn btn-danger" onclick="clearImage()">Clear Image <i class="fa fa-camera" aria-hidden="true"></i></label>
          {% endif %}
        </div>
        <div class="form-group">
          {{ form.first_name|as_crispy_field }}
          {% for error in form.first_name.errors %}
            <span class="help-block">
              {{ error|escape }}
            </span>
          {% endfor %}
        </div>
        <div class="form-group">
          {{ form.last_name|as_crispy_field }}
          {% for error in form.last_name.errors %}
            <span class="help-block">
              {{ error|escape }}
            </span>
          {% endfor %}
        </div>
        <div class="form-group">
          {{ form.title|as_crispy_field }}
          {% for error in form.title.errors %}
            <span class="help-block">
              {{ error|escape }}
            </span>
          {% endfor %}
        </div>
        <div class="form-group">
          {{ form.about|as_crispy_field }}
          {% for error in form.about.errors %}
            <span class="help-block">
              {{ error|escape }}
            </span>
          {% endfor %}
        </div>
        <div class="form-group">
          {{ form.website_url|as_crispy_field }}
          {% for error in form.website_url.errors %}
            <span class="help-block">
              {{ error|escape }}
            </span>
          {% endfor %}
        </div>
        <div class="form-group">
          {{ form.location|as_crispy_field }}
          {% for error in form.location.errors %}
            <span class="help-block">
              {{ error|escape }}
            </span>
          {% endfor %}
        </div>
        <div class="form-group">
          {{ form.phone_number|as_crispy_field }}
          {% for error in form.phone_number.errors %}
            <span class="help-block">
              {{ error|escape }}
            </span>
          {% endfor %}
        </div>
        <div class="form-group">
          <label for="id_areas_of_expertise" class="control-label m-b-5">Areas of expertise</label>
          {{ form.areas_of_expertise }}
          {% for error in form.areas_of_expertise.errors %}
            <span class="help-block">
              {{ error|escape }}
            </span>
          {% endfor %}
        </div>
        <div class="form-group">
          {{ form.areas_of_expertise_other|as_crispy_field }}
          {% for error in form.areas_of_expertise_other.errors %}
            <span class="help-block">
              {{ error|escape }}
            </span>
          {% endfor %}
        </div>
        <div class="form-group">
          <label for="id_languages" class="control-label m-b-5">Languages</label>
          {{ form.languages }}
          {% for error in form.languages.errors %}
            <span class="help-block">
              {{ error|escape }}
            </span>
          {% endfor %}
        </div>
        <div class="form-group">
          {{ form.languages_other|as_crispy_field }}
          {% for error in form.languages_other.errors %}
            <span class="help-block">
              {{ error|escape }}
            </span>
          {% endfor %}
        </div>
        <div class="form-group">
          {{ form.fb_account|as_crispy_field }}
          {% for error in form.fb_account.errors %}
            <span class="help-block">
              {{ error|escape }}
            </span>
          {% endfor %}
        </div>
        <div class="form-group">
          {{ form.twitter_account|as_crispy_field }}
          {% for error in form.twitter_account.errors %}
            <span class="help-block">
              {{ error|escape }}
            </span>
          {% endfor %}
        </div>
        <div class="form-group">
          {{ form.linkedin_account|as_crispy_field }}
          {% for error in form.linkedin_account.errors %}
            <span class="help-block">
              {{ error|escape }}
            </span>
          {% endfor %}
        </div>
        <div class="form-group">
          {{ form.google_account|as_crispy_field }}
          {% for error in form.google_account.errors %}
            <span class="help-block">
              {{ error|escape }}
            </span>
          {% endfor %}
        </div>
        <div class="form-group">
          {{ form.skype|as_crispy_field }}
          {% for error in form.skype.errors %}
            <span class="help-block">
              {{ error|escape }}
            </span>
          {% endfor %}
        </div>
        <strong>Company Information</strong>
      	<br><br>
        <div class="form-group">
          {{ form.company_name|as_crispy_field }}
          {% for error in form.company_name.errors %}
            <span class="help-block">
              {{ error|escape }}
            </span>
          {% endfor %}
        </div>
        <div class="form-group">
          <label for="id_company_logo" class="control-label ">
            Company logo
          </label>
          <div class="hidden">
            {{ form.company_logo|as_crispy_field }}
          </div>
          <br>
          {% if form.company_logo.value != '' %}
            <img src="{{ MEDIA_URL }}{{ form.company_logo.value }}" alt="" class="img-responsive img-thumbnail" width="200" height="200" id="image-logo">
          {% else %}
            <img src="" id="image-logo" class="img-responsive img-thumbnail">
          {% endif %}
          {% for error in form.company_logo.errors %}
            <span class="help-block">
              {{ error|escape }}
            </span>
          {% endfor %}
        </div>
        <div class="row fieldWrapper form-group">
          <label for="id_company_logo" class="btn btn-primary">
            <span>Choose File</span> <i class="fa fa-camera" aria-hidden="true"></i>
          </label>
          {% if form.company_logo.value != '' %}
            <label for="company_logo-clear_id" id="reset-logo" type="button" class="btn btn-danger" onclick="clearLogo()">Clear Image <i class="fa fa-camera" aria-hidden="true"></i></label>
          {% endif %}
        </div>
        <div class="control-group">
          <div class="controls">
            <button type="submit" class="btn">Update</button>
            <a href="{% url 'users:detail' request.user.username %}" class="btn btn-danger">Cancel</a>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}
{% block extra_javascript %}
<script type="text/javascript">
function clearImage(){
  var input = document.getElementById('blah');
    if(input.value){
        try{
            input.value = ''; //for IE11, latest Chrome/Firefox/Opera...
        }catch(err){}
    }
    $('#blah').attr('src', '');
    document.getElementById('blah').style.display = 'none';
    document.getElementById('reset').style.display = 'none';
}
function clearLogo(){
  var input = document.getElementById('image-logo');
    if(input.value){
        try{
            input.value = ''; //for IE11, latest Chrome/Firefox/Opera...
        }catch(err){}
    }
    $('#image-logo').attr('src', '');
    document.getElementById('image-logo').style.display = 'none';
    document.getElementById('reset-logo').style.display = 'none';
}
function upload_img(input) {
  if (input.files && input.files[0]) {
    var reader = new FileReader();
    reader.onload = function (e) {
      $('#blah').attr('src', e.target.result);
      document.getElementById('blah').style.display = 'block';
    }
    reader.readAsDataURL(input.files[0]);
  }
}
$("#id_profile_picture").change(function(input){
  upload_img(this);
});

function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();
      reader.onload = function (e) {
        $('#image-logo').attr('src', e.target.result);
        document.getElementById('image-logo').style.display = 'block';
        document.getElementById('image-logo').style.width = '200px';
      }
      reader.readAsDataURL(input.files[0]);
    }
  }
  $('#id_company_logo').change(function(){
    readURL(this);
  });
</script>
{% endblock extra_javascript %}

seoq/templates/users/user_list.html
{% extends "base.html" %}
{% load static %}{% load i18n %}
{% block title %}Members{% endblock %}

{% block content %}

<div class="container">

    <h2>Users</h2>

    <div class="list-group">
        {% for user in user_list %}
          <a href="{% url 'users:detail' user.username %}" class="list-group-item">
            <h4 class="list-group-item-heading">{{ user.username }}</h4>
          </a>
        {% endfor %}

    </div>

</div>

{% endblock content %}