config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from balystic import views as balystic_views
from ckeditor_uploader import views as ckeditor_views
from seoq.core import views as core_views
from seoq.payments_seoq import views as payments_seoq
from seoq.users.views import UserUpdateRedirect

from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^$', core_views.HomeView.as_view(template_name='pages/home.html'),
        name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'),
        name='about'),
    # Needed cause django-braces uses the account prefix for LoginRequiredMixin
    url(r'^accounts/login/$',
        balystic_views.LoginView.as_view(), name='account_login'),
    url(r'^accounts/login/$',
        balystic_views.LoginView.as_view(), name='balystic_login'),
    url(r'^accounts/logout/$',
        balystic_views.LogoutView.as_view(), name='balystic_logout'),
    url(r'^users/edit/(?P<username>[-\w.+]+)/$',
        UserUpdateRedirect.as_view(),
        name='balystic_user_update'),
    url(r'^accounts/signup/$',
        balystic_views.UserSignupView.as_view(), name='balystic_signup'),
    url(r'^seo-directory/$', core_views.SEODirectoryUserList.as_view(),
        name='directory'),

    url(r'^seo-directory/(?P<username>[\w.@+-]+)/$',
        core_views.PublicUserDetailView.as_view(),
        name='public_profile'),

    url(r'^website-owners/$',
        TemplateView.as_view(template_name='pages/owners.html'),
        name='owners'),
    # url(r'^join/$', TemplateView.as_view(template_name='pages/join.html'),
    #     name='join'),
    url(r'^seo-professionals/$', TemplateView.as_view
        (template_name='pages/professionals.html'),
        name='professionals'),
    url(r'^seo-students/$', TemplateView.as_view
        (template_name='pages/students.html'),
        name='students'),
    url(r'^order/(?P<pk>\d+)/$',
        payments_seoq.OrderView.as_view(), name='order'),
    url(r'^order/(?P<pk>\d+)/payment/success/$',
        payments_seoq.OrderPaymentReturnView.as_view(status='success'),
        name='order_payment_success'),
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),
    url(r'^ckeditor/upload/',
        ckeditor_views.upload, name='ckeditor_upload'),
    url(r'^ckeditor/browse/', ckeditor_views.browse, name='ckeditor_browse'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url('^markdown/', include( 'django_markdown.urls')),

    # User management
    url(r'^', include('seoq.users.urls', namespace='users')),
    # url(r'^qa/.*$',
    #     RedirectView.as_view(
    #         url='http://seoq.app.balystic.com/questions-and-answers/',
    #         permanent=False), name='balystic_qa'),
    url(r'^', include('balystic.urls')),
    url(r'^', include('seoq.seoqtool.urls', namespace='seoqtool')),
    url(r'^', include('plans.urls')),

    # Your stuff: custom urls includes go here
    # CompaniesRedirectView
    url(r'^seo-companies/(?P<slug>[-\w.]+)/$',
        core_views.CompaniesRedirectView.as_view(),
        name='seo_companies_redirect'),
    url(r'^(?P<slug>[-\w.]+)/$',
        core_views.ArchivedBlogRedirectView.as_view(), name='archived_blog'),
    url(r'^robots.txt$', core_views.RobotsView.as_view())

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

seoq/seoqtool/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^www/(?P<netloc>[\w_\-\.]+)/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]{2})/$',
        view=views.ArchiveReportView.as_view(),
        name='archive_report'
    ),
    url(
        regex=r'^add-url/$',
        view=views.CreateReportURLView.as_view(),
        name='add_url'
    ),
]

seoq/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^users/$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # url(
    #     regex=r'^user_list/$',
    #     view=views.UserListTempView.as_view(),
    #     name='list'
    # ),

    # url(
    #     regex=r'^user-list-recent/$',
    #     view=views.UserListMostRecentTempView.as_view(),
    #     name='list'
    # ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^users/~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^users/(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    #URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

seoq/asynchronous/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

seoq/core/forms.py
from django import forms

# our new form
class UserContactForm(forms.Form):
    first_name = forms.CharField(label='First name', required=True)
    last_name = forms.CharField(label='Last name',required=True)
    location = forms.CharField(label='Location',required=True)
    phone = forms.CharField(label='Phone',required=True)
    email = forms.EmailField(label='Email',required=True)
    content = forms.CharField(
        required=True,
        widget=forms.Textarea
    )

    def __init__(self, *args, **kwargs):
        super(UserContactForm, self).__init__(*args, **kwargs)
        for field_name in self.fields:
           field = self.fields.get(field_name)  
           if field:
               field.widget.attrs.update({
               		'placeholder': field.label,
               		'class': 'form-control'
               	})
        self.fields['content'].widget.attrs.update({
    		'placeholder': 'What do you want to say?',
    		'rows': 5
    	})

seoq/seoqtool/forms.py
from django import forms


class ExampleForm(forms.Form):
    url = forms.URLField(required=True, initial='http://')

seoq/asynchronous/views.py
from django.shortcuts import render

# Create your views here.

seoq/core/views.py
import json
from django.shortcuts import render, redirect
from django.views.generic import View, TemplateView
from django.views.generic.base import RedirectView
from django.http import Http404
from django.template.loader import render_to_string
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.conf import settings
from django.contrib import messages
from balystic.client import Client
from seoq.users.models import User
from .forms import UserContactForm


class SEODirectoryUserList(View):
    """
    Displays a list of the users retrieved from 7dhub
    """
    template_name = 'pages/users_directory_page.html'
    client = Client()

    def get(self, request):
        alphabetical = request.GET.get('alphabetical', None)
        query_term = request.GET.get('q', None)
        if query_term is None:
            params = {'isPro': '1', 'alphabetical': '1'}
        else:
            params = {'isPro': '1', 'q': query_term}
        context = {
            'users': self.client.get_users(params=params),
            'query_term': query_term
        }
        context['most_view_users'] = Client().get_users(
            {'sort_type': 'view_count'})['users'][:3]
        context['most_recent_users'] = Client().get_users(
            {'sort_type': 'last_created'})['users'][:3]
        context['most_votes_answer_users'] = Client().get_users(
            {'sort_type': 'answer_vote_count'})['users'][:3]
        context['verified_users'] = Client().get_users(
            {'sort_type': 'verified'})['users'][:3]
        return render(request, self.template_name, context)


class PublicUserDetailView(View):
    template_name = 'users/public_user_detail.html'
    form_class = UserContactForm

    def get(self, request, username):
        user = Client().get_user_detail(username)
        data = user['user'].copy()
        if not isinstance(data['generics'], dict):
            data['generics'] = json.loads(data['generics'])
        data.pop('avatar')
        username = data.pop('username')
        if "error" in user:
            raise Http404
        try:
            data['generics']['view_count'] += 1
        except (KeyError, TypeError):
            data['generics']['view_count'] = 1
        data['generics'] = json.dumps(data['generics'])
        Client().update_user(user['user']['username'], data)
        try:
            user_local = User.objects.get(username=username)
        except User.DoesNotExist:
            user_local = User()
        return render(
            request,
            self.template_name,
            {'user': user, 'user_local': user_local, 'form': self.form_class})

    def post(self, request, username):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            user_email = Client().get_user_detail(username)['user']['email']
            first_name = request.POST.get('first_name')
            last_name = request.POST.get('last_name')
            location = request.POST.get('location')
            phone = request.POST.get('phone')
            email = request.POST.get('email')
            content = request.POST.get('content')
            template = 'users/contact_template.html'
            template = render_to_string(
                template,
                {'form_content': content,
                 'contact_name': first_name + ' ' + last_name,
                 'contact_email': email,
                 'location': location,
                 'phone': phone})
            send_mail(
                first_name + " wants to contact you!",
                None,
                settings.DEFAULT_FROM_EMAIL,
                [user_email],
                html_message=template,
                fail_silently=False)
            messages.success(request, 'Email sent to ' + username)

            return redirect(
                reverse('public_profile', kwargs={'username': username}))


class ArchivedBlogRedirectView(RedirectView):
    """
    Redirect Original blog entries patterns to the new one
    """
    client = Client()

    def get_redirect_url(self, *args, **kwargs):
        slug = self.kwargs.get('slug')

        blog_entry = self.client.get_blog_detail(slug)
        if 'blog' not in blog_entry:
            raise Http404

        return reverse(
            'balystic_blog_detail',
            kwargs={'slug': blog_entry['blog']['slug']})


class CompaniesRedirectView(RedirectView):
    """
    Temporary Redirect of SEO users profiles while profiles are moved
    """
    def get_redirect_url(self, *args, **kwargs):
        slug = self.kwargs.get('slug')
        return settings.SEOQ_COMPANIES_URL + slug


class HomeView(TemplateView):
    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['qscraper_url'] = settings.QSCRAPER_URL
        return context

class RobotsView(TemplateView):
    template_name = 'core/robots.txt'

    def get_context_data(self, **kwargs):
        kwargs['environment'] = settings.PRODUCTION_ENVIRONMENT
        return kwargs

seoq/payments_seoq/views.py
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _
from django.shortcuts import redirect, render
from payments import RedirectNeeded, get_payment_model
from plans.models import Order
from plans.views import OrderView as ParentOrderView
from plans.views import OrderPaymentReturnView as ParentReturnView


class OrderView(ParentOrderView):
    model = Order
    template_name = 'plans/order_detail.html'

    def get_context_data(self, **kwargs):
        context = super(OrderView, self).get_context_data(**kwargs)
        payment, created = get_payment_model().objects.get_or_create(
            order__pk=self.object.pk,
            defaults={
                'variant': 'default',
                'description': 'Plan Purchase',
                'order': self.object,
                'total': self.object.total(),
                'tax': self.object.tax_total(),
                'currency': self.object.currency
            })
        context['payment_form'] = payment.get_form()
        context['payment'] = payment
        return context

    def post(self, request, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        try:
            context['payment_form'] = context['payment'].get_form(
                data=self.request.POST or None)
        except RedirectNeeded as redirect_to:
            return redirect(str(redirect_to))
        return render(request, self.template_name, context)


class OrderPaymentReturnView(ParentReturnView):
    """
    This view is a fallback from any payments processor. It allows just to set
    additional message context and redirect to Order view itself.
    """
    model = Order
    status = None

    def render_to_response(self, context, **response_kwargs):
        if self.status == 'success':
            messages.success(self.request,
                             _('Thank you for placing a payment. \
                                It will be processed as soon as possible.'))
        return redirect('/')

seoq/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView, View, TemplateView
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from balystic.client import Client
from .models import User
from .forms import EditProfileForm
from plans.models import UserPlan

from django.conf import settings


class UserDetailView(View):
    template_name = 'users/user_detail.html'

    def get(self, request, username):
        if not request.user.is_authenticated() or\
           request.user.username != str(username):
            return redirect('public_profile', username=username)
        plan = None
        if self.request.user.is_authenticated():
            plan = UserPlan.objects.get(
                user=self.request.user)
        user = Client().get_user_detail(username)
        owner = Client().get_users({'userType': 'owner'})['owner']
        try:
            local_user = User.objects.get(username=username)
        except User.DoesNotExist:
            pass
        return render(
            request,
            self.template_name,
            {'user': user, 'userplan': plan, 'owner': owner, 'local_user': local_user})


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateRedirect(RedirectView):
    permanent = False

    def get_redirect_url(self, **kwargs):
        return reverse('users:update')


class UserUpdateView(LoginRequiredMixin, UpdateView):

    form_class = EditProfileForm

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail', kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)

    def get(self, request, **kwargs):
        return super(UserUpdateView, self).post(self, request, **kwargs)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


# class UserListTempView(TemplateView):
#     template_name = 'pages/users_directory_temp.html'

#     def get_context_data(self, **kwargs):
#         context = super(UserListTempView, self).get_context_data(**kwargs)
#         params = {'sort_type': 'view_count'}
#         context['users'] = Client().get_users(params)
#         return context


# class UserListMostRecentTempView(TemplateView):
#     template_name = 'pages/users_directory_temp.html'

#     def get_context_data(self, **kwargs):
#         context = super(
#             UserListMostRecentTempView, self).get_context_data(**kwargs)
#         params = {'sort_type': 'last_created'}
#         context['users'] = Client().get_users(params)
#         return context

seoq/templates/base.html
{% load staticfiles active_url i18n compress %}
<!DOCTYPE html>
<html lang="en" xmlns:ng="http://angularjs.org" ng-app="seoq">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block empty_title %}{% block title %}{% endblock title %} | SEO Quotient™{% endblock empty_title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% block meta %}
    <meta name="description" content="SEO Quotient™ provides SEO tools for both website owners and online marketing professionals to diagnose your website and create an action plan.">
    {% endblock meta %}
    <meta name="author" content="">
    <link rel="apple-touch-icon" sizes="57x57" href="{% static "images/favicon.png" %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static "images/favicon.png" %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static "images/favicon.png" %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static "images/favicon.png" %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static "images/favicon.png" %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static "images/favicon.png" %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static "images/favicon.png" %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static "images/favicon.png" %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "images/favicon.png" %}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{% static "images/favicon.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "images/favicon.png" %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static "images/favicon.png" %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "images/favicon.png" %}">
    <link rel="manifest" href="/manifest.json">
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    {% block css %}
    <!-- Your stuff: Third-party css libraries go here -->
    {% compress css %}
    <!-- This file store project specific CSS -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    {% endcompress %}
    {% endblock %}
    <script>
      (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
      function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
      e=o.createElement(i);r=o.getElementsByTagName(i)[0];
      e.src='//www.google-analytics.com/analytics.js';
      r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
      ga('create','UA-3392604-7','auto');ga('send','pageview');
    </script>
  </head>
  <body class="{% block page_class %}{% endblock page_class %}">
    <nav class="navbar navbar-seoq {% block nav_class %}{% endblock nav_class %}">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar" id="#navbar-toggle">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">
          {% block logo %}
            <img src="{% static "images/logo-w.png" %}" alt="SEOQ Logo">
          {% endblock logo %}
          </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar" id="#navbar-toggle">
            <h3>X</h3>
          </button>
          <ul class="nav navbar-nav navbar-right">
            <li {% active_url 'home' %} >
              <a href="{% url 'home' %}">Home</a>
            </li>
            <li {% active_url 'about' %} >
              <a href="{% url 'about' %}">About</a>
            </li>

            <li {% active_url 'owners' %} {% active_url 'professionals' %} {% active_url 'students' %} class="responsive-big">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
              Benefits <span class="caret"></span></a>
              <ul class="dropdown-menu">
              <li {% active_url 'owners' %}><a href="{% url 'owners' %}">Website Owners</a></li>
              <li {% active_url 'professionals' %}><a href="{% url 'professionals' %}">SEO Professionals</a></li>
              <li {% active_url 'students' %}><a href="{% url 'students' %}">SEO Students</a></li>
              </ul>
            </li>
            <li {% active_url 'owners' %} class="responsive" id="item-responsive"><a href="{% url 'owners' %}">Website Owners</a></li>
              <li {% active_url 'professionals' %} class="responsive" id="item-responsive"><a href="{% url 'professionals' %}">SEO Professionals</a></li>
              <li {% active_url 'students' %} class="responsive" id="item-responsive"><a href="{% url 'students' %}">SEO Students</a></li>
            <li {% active_url 'balystic_blog' %}>
              <a href="{% url 'balystic_blog' %}">Blog</a>
            </li>
            <li {% active_url 'directory' %}>
              <a href="{% url 'directory' %}">SEO Directory</a>
            </li>
            <li {% active_url 'pricing' %}>
              <a href="{% url 'pricing' %}">Plans</a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="responsive">
              <a href="{% url 'users:detail' request.user.username %}">{% trans "See Profile" %}</a>
            </li>
            <li class="responsive">
              <a href="{% url 'balystic_logout' %}?next=/">{% trans "Sign out" %}</a>
            </li>
            <!-- dropdown-menu -->
            <li class="responsive-big p-l-10">
              <a class="dropdown-toggle p-0" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false" id="user-dropdown">
                {% if request.user.profile_picture %}
                <img src="{{ request.user.profile_picture.url }}" alt="Profile picture" class="avatar img-circle" width="44px" height="44px">
                {% else %}
                  <img src="{% static 'images/profile-default-thumbnail.jpg' %}" alt="Profile picture" class="img-responsive img-circle" width="44px" height="44px">
                {% endif %}
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'users:detail' request.user.username %}">{% trans "See Profile" %}</a></li>
                <li><a href="{% url 'seoqtool:add_url' %}">{% trans "Create periodic reports" %}</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="{% url 'balystic_logout' %}?next=/">{% trans "Sign out" %}</a></li>
              </ul>
            </li>
            <!-- dropdown-menu -->
            {% else %}
            <li>
              <a href="{% url 'balystic_login' %}" class="text-white text-dark-blue">{% trans "Sign in" %}</a>
            </li>
            <li class="hidden-xs hidden-sm">
              <a href="{% url 'balystic_signup' %}" class="btn btn-lg btn-seoq">
                Join now
              </a>
            </li>
            <li>
              <a href="{% url 'balystic_signup' %}" class="visible-xs visible-sm">Join now</a>
            </li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->

      </div>
    </nav>
    <section class="messages">
      <div class="container-fluid">
        <div class="row">
          {% if messages %}
              {% for message in messages %}
                  <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %} text-center">{{ message }}</div>
              {% endfor %}
          {% endif %}
        </div>
      </div>
    </section>
   {% block content %}
    {% endblock content %}
    <footer class="bg-gray">
      <div class="container p-t-30">
        <div class="row">
          <div class="col-md-12">
            <nav>
              <ul>
                <li>
                  <a href="{% url 'home' %}">Home</a>
                </li>
                <li>
                  <a href="{% url 'about' %}">About</a>
                </li>
                <li>
                  <a href="{% url 'balystic_blog' %}">Blog</a>
                </li>
                <li>
                  <a href="{% url 'directory' %}">SEO Directory</a>
                </li>
                <li>
                  <a href="{% url 'owners' %}">Website Owners</a>
                </li>
                <li>
                  <a href="{% url 'professionals' %}">SEO Professionals</a>
                </li>
                <li>
                  <a href="{% url 'students' %}">SEO Students</a>
                </li>
                <li>
                  <a href="{% url 'balystic_qa' %}">Q&A</a>
                </li>
                <li class="pull-right">
                  <a href="http://m.me/SEOQuotient" target="_blank">Contact Us</a>
                </li>
              </ul>
            </nav>
          </div>
        </div>
      </div>
      <hr class="m-0">
      <div class="container p-t-20">
        <div class="row">
          <div class="col-xs-12 col-md-6">
            2016 SEO Quotient™. All rights reserved
          </div>
          <div class="col-xs-12 col-md-6">
            <div class="row">
              <div class="col-xs-12 col-sm-12 col-md-10 ">
                <ul class="list-inline text-right">
                  <li>
                    <a href="/">
                      <img src="{% static "images/logo-b.png" %}" class="img-responsive footer-logo pull-right">
                    </a>
                  </li>
                  <li>
                    <a href="http://labs.inqbation.com" target="_blank">
                      <img src="{% static "images/inqbation-labs-logo.svg" %}" class="img-responsive footer-logo pull-right" alt="inQbation Labs" target="_blank">
                    </a>
                    <div class="content-social none">
                      <a href="https://facebook.com/seoquotient/" title="Facebook" target="_blank">
                      <i class="fa fa-facebook-square fa-2x"></i>
                      </a>
                      <a href="https://twitter.com/SEOQuotient" title="Twitter" target="_blank">
                        <i class="fa fa-twitter-square fa-2x"></i>
                      </a>
                      <a href="https://plus.google.com/+Seoquotient/" title="Google Plus" target="_blank">
                        <i class="fa fa-google-plus-square fa-2x"></i>
                      </a>
                      <a href="https://www.linkedin.com/company/seo-quotient" title="LinkedIn" target="_blank">
                        <i class="fa fa-linkedin-square fa-2x"></i>
                      </a>
                    </div>
                  </li>
                </ul>
              </div>
              <div class="col-xs-12 col-md-2 ">
                <!-- Social icons -->
                <div class="row">
                  <div class="col-md-12 text-center p-0-6">
                    <a href="https://facebook.com/seoquotient/" title="Facebook" target="_blank">
                      <i class="fa fa-facebook-square fa-2x"></i>
                    </a>
                    <a href="https://twitter.com/SEOQuotient" title="Twitter" target="_blank">
                      <i class="fa fa-twitter-square fa-2x"></i>
                    </a>
                    <a href="https://plus.google.com/+Seoquotient/" title="Google Plus" target="_blank">
                      <i class="fa fa-google-plus-square fa-2x"></i>
                    </a>
                    <a href="https://www.linkedin.com/company/seo-quotient" title="LinkedIn" target="_blank">
                      <i class="fa fa-linkedin-square fa-2x"></i>
                    </a>
                  </div>
                </div>
                <!-- end Social icons -->
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
    {% block modal %}{% endblock modal %}
    {% block javascript %}
      <!-- place project specific Javascript in this file -->
      {% compress js %}
      <script src="{% static 'js/components.js' %}"></script>
      <!--Angular-->
      <script src="{% static 'scripts/app.js' %}"></script>
      <script src="{% static 'scripts/controllers/keyword-score-controller.js' %}"></script>
      <script src="{% static 'scripts/directives/http_prefix.js' %}"></script>
      <!--Project-->
      <script src="{% static 'js/project.js' %}"></script>
      {% endcompress %}
    {% endblock javascript %}
    {% block extra_javascript %}
    {% endblock extra_javascript %}

  </body>
</html>